### ISSUE TITLE
Move multi language choice from "About" to  Header

### ISSUE THREAD

**Issue by AFPMedialab** [AFP-Medialab/invid-verification-plugin#31]
Remove multi language choice fro About page.
Add multi language choice to Header on top right position.
Use Flags+language name in a floating layer

**Comment by laurent-lacroix** [comment]
OK, select of about page is now hidden (but always available if needed). Language can now be changed using links located below we-verify logo. No popup for the moment because without displaying flags and with only 3 activ languages, it's not realy necessary :-) May be later ?
