### ISSUE TITLE
Tutorial layer

### ISSUE THREAD

**Issue by AFPMedialab** [AFP-Medialab/invid-verification-plugin#33]
Add tutorial layer at startup to explain new plugin interface.
Tutorial layer will be an image slide show. Images should be provided
Manage layer with a cookie to avoid it displayed at each start.

**Comment by laurent-lacroix** [comment]
OK, the home popup is now active and can be used to display 1 to 5 images in a carrousel, for each languages. Images must be set in InvidTranslation.tsv (5 fields: home_tutorial_image_1 to home_tutorial_image_5). Leave fields empty if you have less than 5 images.
